a <- read.table("DESeq2_EZH2KO_WT_enrich_padj005_protcod_norm_counts_protcod_logfold_above_below_05_plus1_ratios.txt", sep = "\t", stringsAsFactor = FALSE, header = TRUE)
a$avg <- log(((a$WT_KO_inp1 + a$WT_KO_inp2)/2),2)
a$X.1 <- 1:nrow(a)
a$X.1 <- paste(a$X.1, a$X, sep = "_")
a1 <- a[, c(1,2,7)]
names(a1)[3] <- paste("log2FoldChange")

 library(ggplot2)
 m <- a1
 m1 <- subset(m, m$log2FoldChange < 0)
 m11 <- m1[, c(2)]
 m11 <- data.frame(m11)
 names(m11)[1] <- paste("NAME")
 a <- read.table("T98_EZH2_HsAbcam1.b50.score.width.tss.pergene.EZrep.txt", sep = "\t", header = TRUE, stringsAsFactor = FALSE)
 ma1 <- merge(a, m11, by = "NAME")
 ma1 <- ma1[, -c(1,2)]
 mat <- t(ma1)
 h <- apply(as.matrix(mat), 1, function(x){mean(x)+c(-1.96,0,1.96)*sd(x)/sqrt(length(x))})
 h <- data.frame(h)
 ht <- t(h)
 ht <- data.frame(ht)
 names(ht)[1] <- paste("lower")
 names(ht)[2] <- paste("mean")
 names(ht)[3] <- paste("upper")
 ht$type <- paste("EZH2_repressed")
 ht$X <- 1:nrow(ht)
 p <- ht
 m1 <- subset(m, m$log2FoldChange > 0)
 m11 <- m1[, c(2)]
 m11 <- data.frame(m11)
 names(m11)[1] <- paste("NAME")
 ma1 <- merge(a, m11, by = "NAME")
 ma1 <- ma1[, -c(1,2)]
 mat <- t(ma1)
 h <- apply(as.matrix(mat), 1, function(x){mean(x)+c(-1.96,0,1.96)*sd(x)/sqrt(length(x))})
 h <- data.frame(h)
 ht <- t(h)
 ht <- data.frame(ht)
 names(ht)[1] <- paste("lower")
 names(ht)[2] <- paste("mean")
 names(ht)[3] <- paste("upper")
 ht$type <- paste("EZH2_activated")
 ht$X <- 1:nrow(ht)
 q <- rbind(p, ht)
 write.csv(q, "EZH2_ChIP_diff_genes_avg_plot.csv")
 pdf("EZH2_ChIP_diff_genes_avg_plot.pdf")
 p<-ggplot(data=q, aes(x=X, y=mean, colour = type)) + geom_line(size =1)
 p + theme_bw() + geom_ribbon(aes(ymin=lower, ymax=upper, fill = type), linetype=0, alpha=0.5) + scale_color_manual(values=c("yellow3", "darkcyan")) + scale_fill_manual(values=c("yellow3", "darkcyan"))
 dev.off()

 m1 <- subset(m, m$log2FoldChange < 0)
 m11 <- m1[, c(2)]
 m11 <- data.frame(m11)
 names(m11)[1] <- paste("NAME")
 a <- read.table("T98_H3k27me3_HsCmb.b50.score.width.tss.pergene.EZrep.txt", sep = "\t", header = TRUE, stringsAsFactor = FALSE)
 ma1 <- merge(a, m11, by = "NAME")
 ma1 <- ma1[, -c(1,2)]
 mat <- t(ma1)
 h <- apply(as.matrix(mat), 1, function(x){mean(x)+c(-1.96,0,1.96)*sd(x)/sqrt(length(x))})
 h <- data.frame(h)
 ht <- t(h)
 ht <- data.frame(ht)
 names(ht)[1] <- paste("lower")
 names(ht)[2] <- paste("mean")
 names(ht)[3] <- paste("upper")
 ht$type <- paste("EZH2_repressed")
 ht$X <- 1:nrow(ht)
 p <- ht
 m1 <- subset(m, m$log2FoldChange > 0)
 m11 <- m1[, c(2)]
 m11 <- data.frame(m11)
 names(m11)[1] <- paste("NAME")
 ma1 <- merge(a, m11, by = "NAME")
 ma1 <- ma1[, -c(1,2)]
 mat <- t(ma1)
 h <- apply(as.matrix(mat), 1, function(x){mean(x)+c(-1.96,0,1.96)*sd(x)/sqrt(length(x))})
 h <- data.frame(h)
 ht <- t(h)
 ht <- data.frame(ht)
 names(ht)[1] <- paste("lower")
 names(ht)[2] <- paste("mean")
 names(ht)[3] <- paste("upper")
 ht$type <- paste("EZH2_activated")
 ht$X <- 1:nrow(ht)
 q <- rbind(p, ht)
 write.csv(q, "H3K27me3_b1_ChIP_diff_genes_avg_plot.csv")
 pdf("H3K27me3_b1_ChIP_diff_genes_avg_plot.pdf")
 p<-ggplot(data=q, aes(x=X, y=mean, colour = type)) + geom_line(size =1)
 p + theme_bw() + geom_ribbon(aes(ymin=lower, ymax=upper, fill = type), linetype=0, alpha=0.5) + scale_color_manual(values=c("yellow3", "darkcyan")) + scale_fill_manual(values=c("yellow3", "darkcyan"))
 dev.off()

 
 m1 <- subset(m, m$log2FoldChange < 0)
 m11 <- m1[, c(2)]
 m11 <- data.frame(m11)
 names(m11)[1] <- paste("NAME")
 a <- read.table("t98_h3k4me3_b1.b50.score.width.tss.pergene.EZrep.txt", sep = "\t", header = TRUE, stringsAsFactor = FALSE)
 ma1 <- merge(a, m11, by = "NAME")
 ma1 <- ma1[, -c(1,2)]
 mat <- t(ma1)
 h <- apply(as.matrix(mat), 1, function(x){mean(x)+c(-1.96,0,1.96)*sd(x)/sqrt(length(x))})
  h <- data.frame(h)
 ht <- t(h)
 ht <- data.frame(ht)
 names(ht)[1] <- paste("lower")
 names(ht)[2] <- paste("mean")
 names(ht)[3] <- paste("upper")
 ht$type <- paste("EZH2_repressed")
 ht$X <- 1:nrow(ht)
 p <- ht
 m1 <- subset(m, m$log2FoldChange > 0)
 m11 <- m1[, c(2)]
 m11 <- data.frame(m11)
 names(m11)[1] <- paste("NAME")
 ma1 <- merge(a, m11, by = "NAME")
 ma1 <- ma1[, -c(1,2)]
 mat <- t(ma1)
 h <- apply(as.matrix(mat), 1, function(x){mean(x)+c(-1.96,0,1.96)*sd(x)/sqrt(length(x))})
 h <- data.frame(h)
 ht <- t(h)
 ht <- data.frame(ht)
 names(ht)[1] <- paste("lower")
 names(ht)[2] <- paste("mean")
 names(ht)[3] <- paste("upper")
 ht$type <- paste("EZH2_activated")
 ht$X <- 1:nrow(ht)
 q <- rbind(p, ht)
 write.csv(q, "H3K4me3_b1_ChIP_diff_genes_avg_plot.csv")
 pdf("H3K4me3_ChIP_diff_genes_avg_plot.pdf")
 p<-ggplot(data=q, aes(x=X, y=mean, colour = type)) + geom_line(size =1)
 p + theme_bw() + geom_ribbon(aes(ymin=lower, ymax=upper, fill = type), linetype=0, alpha=0.5) + scale_color_manual(values=c("yellow3", "darkcyan")) + scale_fill_manual(values=c("yellow3", "darkcyan"))
 dev.off()

